### ISSUE TITLE
QR code doesn't show in the Tor Browser

### ISSUE THREAD

**Issue by openoms** [lnproxy/lnproxy-webui2#2]
Using http://dx7pn6ehykq6cadce4bjbxn5tf64z7e3fufpxgxce7n4f5eja476cpyd.onion/ in the latest Tor Browser 12.0.5 (based on Mozilla Firefox 102.10.0esr) (64-bit)

The QRcode of the wrapped invoice doesn't show properly:
![image](https://user-images.githubusercontent.com/43343391/234028820-6787012e-dad7-46e9-96c5-81d45bc935b5.png)

Should be easy to reproduce.

**Comment by openoms** [comment]
Found the reason in https://github.com/joinmarket-webui/jam/issues/190 and it solved by giving `Extract canvas data permission` to the site with the icon left from the URL. 
The problem is that it needs to be activated before the QR code is generated so I can think of some ways to address this:
* generate the QRcode in a different way not needing extra permission
* instructions (and maybe a little sample QRcode) on the lnproxy start page
* intructions and an option to regenerate the QRcode on the wrapped invoice page

**Comment by lnproxy** [comment]
Whoa, kind of pretty bug there.

Thanks for reporting.  This definitely needs a fix, the previous webui generated the qr server side so it worked without any permissions (even js) on tor.  Might be an easy fix, the qrcode library I'm using is supposed to use a table to make the qrcode if canvas is not supported.

**Comment by lnproxy** [comment]
Latest commit should fix this

**Comment by openoms** [comment]
Works great, thanks!
