### ISSUE TITLE
Vague error when wrapping the same invoice twice

### ISSUE THREAD

**Issue by ghost** [lnproxy/lnproxy-webui2#5]
If a user wraps an invoice, but then tries to wrap the same invoice again, the UI displays a generic "Internal Error". A user could want to retry wrapping in couple of example use cases such as a connection timeout, they accidentally closed the tab, or they lost the wrapped invoice some other way. In all cases they need to retry wrapping it.

The UI should ideally display a more descriptive error message in this scenario.

<img width="641" alt="image" src="https://github.com/lnproxy/lnproxy-webui2/assets/116033104/eb85d0c7-2bac-4d83-be09-84b6aadc04bb">

**Comment by lnproxy** [comment]
Yup, error should be better.  Thanks for opening the issue.

**Comment by lnproxy** [comment]
OK, error message should read "an invoice with that payment hash already exists"

It may make sense to simply replace the old invoice with a new one, but I'd have to think more carefully about that.
